site_name: Polish Club Notes
site_url: https://glindstrom.github.io/polish-club-notes/
strict: true
docs_dir: docs
site_dir: site
theme:
  name: material
  palette:
    primary: indigo
    accent: blue
  toc:
    depth: 2
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.copy
    - content.tabs.link
markdown_extensions:
  - tables
  - fenced_code
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      toc_depth: 2
plugins:
  - search
nav:
  - Home: index.md
  - Openings:
      - Opening Bids: openings/overview.md
      - 1♣ Opening: openings/one-club.md
      - 1♣ Interference: openings/one-club-interference.md
      - 1♦ Opening: openings/one-diamond.md
      - 1♦ Interference: openings/one-diamond-interference.md
      - 1♥ Opening: openings/one-heart.md
      - 1♠ Opening: openings/one-spade.md
      - 1♥/1♠ Interference: openings/one-heart-one-spade-interference.md
      - 1NT Opening: openings/one-nt.md
      - 1NT Interference: openings/one-nt-interference.md
      - Preemptive Openings Overview: openings/preemptive-openings.md
      - 2♣ Opening: openings/two-club.md
      - 2♣ Interference: openings/two-club-interference.md
      - 2♦ Opening: openings/two-diamond.md
      - 2♦ Interference: openings/two-diamond-interference.md
      - 2♥/2♠ Openings: openings/two-major.md
      - 2♥/2♠ Interference: openings/two-major-interference.md
      - 2NT Opening: openings/two-nt.md
      - Three-Level Openings: openings/three-level-openings.md
      - Four-Level Openings: openings/four-level-openings.md
  - Competitive Bidding in Defence:
      - Overview: competitive-bidding/overview.md
      - Attacking-Defensive Double: competitive-bidding/attacking-defensive-double.md
      - Defence Against Specific Openings: competitive-bidding/defence-specific-openings.md
      - General Principles: competitive-bidding/general-principles.md
      - Overcalls at the One Level: competitive-bidding/overcalls-one-level.md
      - Overcalls at the Two Level and Higher: competitive-bidding/overcalls-two-level.md
      - Take-Out Doubles: competitive-bidding/take-out-doubles.md
      - NT Overcalls: competitive-bidding/nt-overcalls.md
      - Two-Suited Overcalls: competitive-bidding/two-suited-overcalls.md
  - After Intervention:
      - Overview: after-intervention/overview.md
      - Two-Suited Bids: after-intervention/two-suited-bids.md
      - Bidding After Major Suit Agreement: after-intervention/bidding-after-major-suit-agreement.md
      - Support Double and Redouble: after-intervention/support-double-redouble.md
  - Conventions:
      - Overview: conventions/overview.md
      - 2NT Forcing: conventions/two-nt-forcing.md
      - Checkback: conventions/checkback.md
      - Drury: conventions/drury.md
      - Fourth Suit Forcing: conventions/fourth-suit.md
      - Jump in Opponent's Suit: conventions/jump-to-opponents-suit.md
      - Odwrotka: conventions/odwrotka.md
      - Shortness Ask: conventions/short-suit-ask.md
      - Third Suit Forcing: conventions/third-suit.md
  - Slam Bidding: 
      - Overview: slam-bidding/overview.md
      - Keycard Blackwood: slam-bidding/blackwood.md
      - Cue Bidding: slam-bidding/cue-bidding.md
      - 5 NT Slam Conventions: slam-bidding/five-nt-slam-conventions.md
      - 5 in Agreed Major: slam-bidding/five-level-major.md
      - Specific King Ask: slam-bidding/specific-king-ask.md
  - Hand Evaluation: hand-evaluation.md
  - Carding Agreements: carding-agreements.md
extra_css:
  - css/custom.css